### ISSUE TITLE
bug in file examples/cookie.lua?

### ISSUE THREAD

**Issue by javatmn** [kernelsauce/turbo#149]
i found that i need to exchange the line of below codes to make cookie "counter" increase,
----
 self:write("Cookie counter is at: " .. new_count)
self:set_cookie("counter", new_count)  -- should be called before self:write()!
-----

I use firefox browser.

**Comment by kernelsauce** [comment]
Yes, I will fix that. Seems like a line has snuck in there somehow...

**Comment by kernelsauce** [comment]
Fixed in luasocket branch.

**Comment by ryannining** [comment]
I have swap the line to 
```
    local counter = self:get_cookie("counter") 
    local new_count = counter and tonumber(counter) + 1 or 0
    self:set_cookie("id", "supersecretrandomid!") -- Set cookie for one year.
    self:set_cookie("counter", new_count) 
    self:write("Cookie counter is at: " .. new_count)
```

Still get only `Cookie counter is at: 0` at web browser, i am using chrome. I using download from v.1.1

**Comment by kernelsauce** [comment]
Try the master branch.
